In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

## The first column is the population of a city and the second column is the profit of a food truck in that city. A negative value for profit indicates a loss.

In [2]:
data = pd.read_csv('ex1data1.txt', sep=',', names=['Population', 'Profit'])

In [3]:
data.head()

Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [4]:
X = np.array([data['Population']]).reshape(97,1)
m = X.shape[0]
X = np.hstack((np.ones((m,1)),X))

In [5]:
y = np.array([data['Profit']]).reshape(m, 1)
theta = np.zeros((X.shape[1], 1))

In [6]:
def compute_cost(X, y, params):
    h = X @ params
    sqr = (h-y) ** 2
    j = (1/(2*m)) * sqr.sum()
    return j

In [7]:
# test_theta = np.array([-1, 2]).reshape(2, 1)
c = compute_cost(X, y, theta)

In [8]:
def gradient_descent(X, y, params, alpha, iteration):
    j_history = np.zeros((iteration, 1))
    
    for i in range(iteration):
        h = X @ params
        p = (h-y).T
        params = params - ((alpha / m) * (p @ X).T )
        
        j_history[i] = compute_cost(X, y, params)
    return (params, j_history)

In [9]:
t, j = gradient_descent(X, y, theta, 0.01, 1500)

In [10]:
print(f'Cost when theta=[0, 0], {c}\n')
print(f'Theta after 1500 iteration: \n{t}\n\n')

print(f'First 50 cost: \n{j[:50, :]}\n\n')

print(f'Last 50 cost: \n{j[-50:, :]}\n\n')

Cost when theta=[0, 0], 32.072733877455676

Theta after 1500 iteration: 
[[-3.63029144]
 [ 1.16636235]]


First 50 cost: 
[[6.73719046]
 [5.93159357]
 [5.90115471]
 [5.89522859]
 [5.89009494]
 [5.88500416]
 [5.87993248]
 [5.87487909]
 [5.86984391]
 [5.86482687]
 [5.85982789]
 [5.85484692]
 [5.84988389]
 [5.84493874]
 [5.8400114 ]
 [5.83510181]
 [5.8302099 ]
 [5.82533562]
 [5.82047889]
 [5.81563965]
 [5.81081784]
 [5.8060134 ]
 [5.80122627]
 [5.79645638]
 [5.79170367]
 [5.78696808]
 [5.78224955]
 [5.77754801]
 [5.77286341]
 [5.76819568]
 [5.76354477]
 [5.75891061]
 [5.75429313]
 [5.7496923 ]
 [5.74510803]
 [5.74054027]
 [5.73598897]
 [5.73145406]
 [5.72693549]
 [5.72243319]
 [5.71794711]
 [5.71347718]
 [5.70902336]
 [5.70458558]
 [5.70016379]
 [5.69575792]
 [5.69136792]
 [5.68699373]
 [5.6826353 ]
 [5.67829257]]


Last 50 cost: 
[[4.48462934]
 [4.48460175]
 [4.48457427]
 [4.48454689]
 [4.4845196 ]
 [4.48449241]
 [4.48446532]
 [4.48443833]
 [4.48441143]
 [4.48438463]
 [4.48435793]
 [4.48

In [11]:
def predict_value(X, theta):
    return X @ theta

* For population = 35,000, we predict a profit of 4519.767868 
* For population = 70,000, we predict a profit of 45342.45012

In [51]:
val = 35000 / 10000
x = np.array([1, val]).reshape(1, 2)

In [52]:
print(predict_value(x, t)[0, 0] * 10000)

4519.7678677017675


In [53]:
reg = linear_model.LinearRegression()
reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [54]:
# theta from sklearn
t1 = reg.coef_[0,1]
t2 = reg.intercept_[0]
sk_theta = np.array([t2, t1]).reshape(2, 1)
sk_theta

array([[-3.89578088],
       [ 1.19303364]])

In [55]:
predict_value(x, sk_theta)[0,0] * 10000

2798.368763517232

In [56]:
sklearn_accuracy = reg.score(X, y) * 100

In [57]:
def our_score(X, y, params):
    h = X @ params
    p = ((y - h) ** 2).sum()
    e = ((y - y.mean()) ** 2).sum()
    score = 1 - (p / e)
    return score

In [58]:
our_accuracy = our_score(X, y, t) * 100

In [65]:
print('SkLearn training accuracy = {:.4f}%\n\nOur training accuracy = {:.4f}%\n'.format(sklearn_accuracy, our_accuracy))

SkLearn training accuracy = 0.7020%

Our training accuracy = 0.7016%

